"""Code generator service for creating Temporal workflows from graphs."""

from typing import List, Dict, Any
import json

from src.config.defaults import (
    DEFAULT_ACTIVITY_MAX_ATTEMPTS,
    DEFAULT_ACTIVITY_TIMEOUT_SECONDS,
    MAX_ACTIVITY_RETRY_ATTEMPTS,
)


class CodeGeneratorService:
    """Generates Temporal workflow Python code from graph structures."""

    def __init__(self):
        pass

    def generate_workflow_from_graph(
        self,
        workflow_name: str,
        graph_data: Dict[str, Any],
        activity_operations: Dict[int, Dict[str, str]],
    ) -> str:
        """
        Generate Temporal workflow code from a graph structure.

        Args:
            workflow_name: Name of the workflow class
            graph_data: Graph structure with nodes and edges
            activity_operations: Map of activity_operation_id -> {code_symbol, name}

        Returns:
            Generated Python module code
        """
        nodes = graph_data.get("nodes", [])
        edges = graph_data.get("edges", [])
        entry_node_id: int = graph_data.get("entry_node_id", 0)

        # Build execution order from edges
        execution_order = self._build_execution_order(nodes, edges, entry_node_id)

        # Generate imports
        imports = self._generate_imports(nodes, activity_operations)

        # Generate workflow class
        workflow_class = self._generate_workflow_class(
            workflow_name, execution_order, nodes, edges, activity_operations
        )

        # Combine into module
        module_code = f'''"""
Auto-generated Temporal workflow: {workflow_name}
Generated by Tapcraft Agent
"""

{imports}


{workflow_class}
'''

        return module_code

    def _generate_imports(
        self, nodes: List[Dict], activity_operations: Dict[int, Dict[str, str]]
    ) -> str:
        """Generate import statements."""
        imports = [
            "from temporalio import workflow",
            "from temporalio.common import RetryPolicy",
            "from datetime import timedelta",
            "from typing import Dict, Any",
        ]

        return "\n".join(imports)

    def _build_execution_order(
        self, nodes: List[Dict], edges: List[Dict], entry_node_id: int
    ) -> List[int]:
        """Build a simple linear execution order from the graph."""
        # For now, just do a simple traversal from entry node
        # TODO: Handle branching, loops, etc.

        if not entry_node_id:
            return [n["id"] for n in nodes if n["kind"] != "trigger"]

        # Build adjacency list
        adjacency: Dict[int, List[int]] = {}
        for edge in edges:
            from_id = edge["from_node_id"]
            to_id = edge["to_node_id"]
            if from_id not in adjacency:
                adjacency[from_id] = []
            adjacency[from_id].append(to_id)

        # Simple DFS traversal
        order = []
        visited = set()

        def dfs(node_id):
            if node_id in visited:
                return
            visited.add(node_id)
            order.append(node_id)
            if node_id in adjacency:
                for next_id in adjacency[node_id]:
                    dfs(next_id)

        dfs(entry_node_id)

        return order

    def _generate_workflow_class(
        self,
        workflow_name: str,
        execution_order: List[int],
        nodes: List[Dict],
        edges: List[Dict],
        activity_operations: Dict[int, Dict[str, str]],
    ) -> str:
        """Generate the workflow class definition."""

        # Create node lookup
        nodes_by_id = {n["id"]: n for n in nodes}

        # Generate workflow steps
        steps = []
        for idx, node_id in enumerate(execution_order):
            node = nodes_by_id.get(node_id)
            if not node:
                continue

            # Skip trigger nodes
            if node["kind"] == "trigger":
                continue

            step_code = self._generate_step(node, idx, activity_operations)
            if step_code:
                steps.append(step_code)

        steps_code = "\n\n".join(steps)

        # Generate workflow class
        class_code = f'''@workflow.defn
class {workflow_name}:
    """Auto-generated workflow."""

    @workflow.run
    async def run(self, cfg: Dict[str, Any]) -> Dict[str, Any]:
        """Execute the workflow."""
        workflow.logger.info(f"Starting workflow with config: {{cfg}}")

        results = {{}}

{self._indent(steps_code, 2)}

        workflow.logger.info(f"Workflow completed with results: {{results}}")
        return results
'''

        return class_code

    def _parse_error_handling(self, config: str) -> Dict[str, Any]:
        """Extract retry policy and timeout settings from node config.

        Enforces platform guardrails: retry attempts are capped at
        MAX_ACTIVITY_RETRY_ATTEMPTS to prevent infinite retry loops.
        """
        try:
            cd = json.loads(config) if isinstance(config, str) else config
        except (json.JSONDecodeError, TypeError):
            cd = {}

        raw_attempts = cd.get("_retry_max_attempts", DEFAULT_ACTIVITY_MAX_ATTEMPTS)
        capped_attempts = min(int(raw_attempts), MAX_ACTIVITY_RETRY_ATTEMPTS)

        return {
            "retry_max_attempts": capped_attempts,
            "retry_initial_interval": cd.get("_retry_initial_interval", 1),
            "retry_backoff": cd.get("_retry_backoff_coefficient", 2.0),
            "retry_max_interval": cd.get("_retry_max_interval", 60),
            "stc_timeout": cd.get("_start_to_close_timeout", DEFAULT_ACTIVITY_TIMEOUT_SECONDS),
            "stsc_timeout": cd.get("_schedule_to_close_timeout"),
        }

    def _gen_retry(self, eh: Dict[str, Any]) -> str:
        """Generate RetryPolicy(...) code."""
        parts = [f"maximum_attempts={eh['retry_max_attempts']}"]
        if eh["retry_initial_interval"] != 1:
            parts.append(f"initial_interval=timedelta(seconds={eh['retry_initial_interval']})")
        if eh["retry_backoff"] != 2.0:
            parts.append(f"backoff_coefficient={eh['retry_backoff']}")
        if eh["retry_max_interval"] != 60:
            parts.append(f"maximum_interval=timedelta(seconds={eh['retry_max_interval']})")
        return f"RetryPolicy({', '.join(parts)})"

    def _gen_timeouts(self, eh: Dict[str, Any]) -> str:
        """Generate timeout keyword arguments."""
        args = [f"start_to_close_timeout=timedelta(seconds={eh['stc_timeout']})"]
        if eh["stsc_timeout"]:
            args.append(f"schedule_to_close_timeout=timedelta(seconds={eh['stsc_timeout']})")
        return ",\n    ".join(args)

    def _strip_eh_keys(self, config: str) -> str:
        """Return JSON config string with error-handling keys removed."""
        try:
            cd = json.loads(config) if isinstance(config, str) else config
            return json.dumps({k: v for k, v in cd.items() if not k.startswith("_")})
        except (json.JSONDecodeError, TypeError):
            return config

    def _generate_step(
        self, node: Dict, step_idx: int, activity_operations: Dict[int, Dict[str, str]]
    ) -> str:
        """Generate code for a single workflow step."""

        kind = node["kind"]
        label = node["label"]
        config = node.get("config", "{}")
        eh = self._parse_error_handling(config)

        if kind == "activity_operation":
            op_id = node.get("activity_operation_id")
            if not op_id or op_id not in activity_operations:
                return f"# TODO: Unknown activity operation {op_id}"

            activity_name = activity_operations[op_id]["code_symbol"]
            clean = self._strip_eh_keys(config)
            rp = self._gen_retry(eh)
            to = self._gen_timeouts(eh)

            return f"""# Step {step_idx + 1}: {label}
step_{step_idx}_result = await workflow.execute_activity(
    "{activity_name}",
    args=[{clean}],
    {to},
    retry_policy={rp},
)
results["step_{step_idx}"] = step_{step_idx}_result
workflow.logger.info(f"Completed step {step_idx + 1}: {label}")
"""

        elif kind == "primitive":
            primitive_type = node.get("primitive_type", "unknown")
            rp = self._gen_retry(eh)
            to = self._gen_timeouts(eh)

            if primitive_type == "http_request":
                clean = self._strip_eh_keys(config)
                return f"""# Step {step_idx + 1}: {label} (HTTP Request)
step_{step_idx}_result = await workflow.execute_activity(
    "net.http.request",
    args=[{clean}],
    {to},
    retry_policy={rp},
)
results["step_{step_idx}"] = step_{step_idx}_result
"""

            elif primitive_type == "delay":
                try:
                    cd = json.loads(config) if isinstance(config, str) else config
                    seconds = cd.get("seconds", 60)
                except (json.JSONDecodeError, TypeError):
                    seconds = 60

                return f"""# Step {step_idx + 1}: {label} (Delay)
workflow.logger.info("Sleeping for {seconds} seconds")
await workflow.sleep({seconds})
results["step_{step_idx}"] = {{"status": "slept", "seconds": {seconds}}}
"""

            elif primitive_type == "browse":
                clean = self._strip_eh_keys(config)
                return f"""# Step {step_idx + 1}: {label} (Browse)
step_{step_idx}_result = await workflow.execute_activity(
    "browse_page",
    args=[{clean}],
    {to},
    retry_policy={rp},
)
results["step_{step_idx}"] = step_{step_idx}_result
workflow.logger.info(f"Completed browse step: {label}")
"""

            elif primitive_type == "log":
                try:
                    cd = json.loads(config) if isinstance(config, str) else config
                    message = cd.get("message", "Log step executed")
                    level = cd.get("level", "info")
                except (json.JSONDecodeError, TypeError):
                    message = "Log step executed"
                    level = "info"

                safe_msg = message.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")

                return f"""# Step {step_idx + 1}: {label} (Log)
workflow.logger.{level}("{safe_msg}")
results["step_{step_idx}"] = {{"logged": True, "message": "{safe_msg}"}}
"""

        elif kind == "logic":
            return f"# TODO: Logic node - {label}"

        return f"# TODO: Unknown node kind - {kind}"

    def _indent(self, text: str, levels: int = 1) -> str:
        """Indent text by the specified number of levels."""
        indent = "    " * levels
        return "\n".join(indent + line if line.strip() else line for line in text.split("\n"))
