"""Code generator service for creating Temporal workflows from graphs."""

from typing import List, Dict, Any
import json


class CodeGeneratorService:
    """Generates Temporal workflow Python code from graph structures."""

    def __init__(self):
        pass

    def generate_workflow_from_graph(
        self,
        workflow_name: str,
        graph_data: Dict[str, Any],
        app_operations: Dict[int, Dict[str, str]],
    ) -> str:
        """
        Generate Temporal workflow code from a graph structure.

        Args:
            workflow_name: Name of the workflow class
            graph_data: Graph structure with nodes and edges
            app_operations: Map of app_operation_id -> {code_symbol, name}

        Returns:
            Generated Python module code
        """
        nodes = graph_data.get("nodes", [])
        edges = graph_data.get("edges", [])
        entry_node_id = graph_data.get("entry_node_id")

        # Build execution order from edges
        execution_order = self._build_execution_order(nodes, edges, entry_node_id)

        # Generate imports
        imports = self._generate_imports(nodes, app_operations)

        # Generate workflow class
        workflow_class = self._generate_workflow_class(
            workflow_name, execution_order, nodes, edges, app_operations
        )

        # Combine into module
        module_code = f'''"""
Auto-generated Temporal workflow: {workflow_name}
Generated by Tapcraft Agent
"""

{imports}


{workflow_class}
'''

        return module_code

    def _generate_imports(
        self, nodes: List[Dict], app_operations: Dict[int, Dict[str, str]]
    ) -> str:
        """Generate import statements."""
        imports = [
            "from temporalio import workflow",
            "from datetime import timedelta",
            "from typing import Dict, Any",
        ]

        return "\n".join(imports)

    def _build_execution_order(
        self, nodes: List[Dict], edges: List[Dict], entry_node_id: int
    ) -> List[int]:
        """Build a simple linear execution order from the graph."""
        # For now, just do a simple traversal from entry node
        # TODO: Handle branching, loops, etc.

        if not entry_node_id:
            return [n["id"] for n in nodes if n["kind"] != "trigger"]

        # Build adjacency list
        adjacency = {}
        for edge in edges:
            from_id = edge["from_node_id"]
            to_id = edge["to_node_id"]
            if from_id not in adjacency:
                adjacency[from_id] = []
            adjacency[from_id].append(to_id)

        # Simple DFS traversal
        order = []
        visited = set()

        def dfs(node_id):
            if node_id in visited:
                return
            visited.add(node_id)
            order.append(node_id)
            if node_id in adjacency:
                for next_id in adjacency[node_id]:
                    dfs(next_id)

        dfs(entry_node_id)

        return order

    def _generate_workflow_class(
        self,
        workflow_name: str,
        execution_order: List[int],
        nodes: List[Dict],
        edges: List[Dict],
        app_operations: Dict[int, Dict[str, str]],
    ) -> str:
        """Generate the workflow class definition."""

        # Create node lookup
        nodes_by_id = {n["id"]: n for n in nodes}

        # Generate workflow steps
        steps = []
        for idx, node_id in enumerate(execution_order):
            node = nodes_by_id.get(node_id)
            if not node:
                continue

            # Skip trigger nodes
            if node["kind"] == "trigger":
                continue

            step_code = self._generate_step(node, idx, app_operations)
            if step_code:
                steps.append(step_code)

        steps_code = "\n\n".join(steps)

        # Generate workflow class
        class_code = f'''@workflow.defn
class {workflow_name}:
    """Auto-generated workflow."""

    @workflow.run
    async def run(self, cfg: Dict[str, Any]) -> Dict[str, Any]:
        """Execute the workflow."""
        workflow.logger.info(f"Starting workflow with config: {{cfg}}")

        results = {{}}

{self._indent(steps_code, 2)}

        workflow.logger.info(f"Workflow completed with results: {{results}}")
        return results
'''

        return class_code

    def _generate_step(
        self, node: Dict, step_idx: int, app_operations: Dict[int, Dict[str, str]]
    ) -> str:
        """Generate code for a single workflow step."""

        kind = node["kind"]
        label = node["label"]
        config = node.get("config", "{}")

        if kind == "app_operation":
            # Get operation details
            op_id = node.get("app_operation_id")
            if not op_id or op_id not in app_operations:
                return f'# TODO: Unknown app operation {op_id}'

            op_info = app_operations[op_id]
            activity_name = op_info["code_symbol"]

            # Parse config
            try:
                config_dict = json.loads(config) if isinstance(config, str) else config
                config_str = json.dumps(config_dict)
            except:
                config_str = "{}"

            step_code = f'''# Step {step_idx + 1}: {label}
step_{step_idx}_result = await workflow.execute_activity(
    "{activity_name}",
    args=[{config_str}],
    start_to_close_timeout=timedelta(seconds=300),
    retry_policy=workflow.RetryPolicy(maximum_attempts=3),
)
results["step_{step_idx}"] = step_{step_idx}_result
workflow.logger.info(f"Completed step {step_idx + 1}: {label}")
'''
            return step_code

        elif kind == "primitive":
            primitive_type = node.get("primitive_type", "unknown")

            if primitive_type == "http_request":
                step_code = f'''# Step {step_idx + 1}: {label} (HTTP Request)
step_{step_idx}_result = await workflow.execute_activity(
    "net.http.request",
    args=[{config}],
    start_to_close_timeout=timedelta(seconds=300),
)
results["step_{step_idx}"] = step_{step_idx}_result
'''
                return step_code

            elif primitive_type == "delay":
                try:
                    config_dict = json.loads(config) if isinstance(config, str) else config
                    seconds = config_dict.get("seconds", 60)
                except:
                    seconds = 60

                step_code = f'''# Step {step_idx + 1}: {label} (Delay)
workflow.logger.info("Sleeping for {seconds} seconds")
await workflow.sleep({seconds})
results["step_{step_idx}"] = {{"status": "slept", "seconds": {seconds}}}
'''
                return step_code

        elif kind == "logic":
            # TODO: Handle conditional logic
            return f'# TODO: Logic node - {label}'

        return f'# TODO: Unknown node kind - {kind}'

    def _indent(self, text: str, levels: int = 1) -> str:
        """Indent text by the specified number of levels."""
        indent = "    " * levels
        return "\n".join(indent + line if line.strip() else line for line in text.split("\n"))
